<?php
/**
 * This class is generated by makeActionForm tool.
 * @package   Legacy
 * @version   2.3.0
 * @author    Gigamaster, XCL 2020 PHP7
 * @author    code generator makeActionForm
 * @copyright Copyright 2005-2021 XOOPS Cube Project  <https://github.com/xoopscube/legacy>
 * @license   https://github.com/xoopscube/legacy/blob/master/docs/GPL_V2.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @license   https://github.com/xoopscube/legacy/blob/master/docs/bsd_licenses.txt Modified BSD license
 */

if (!defined('XOOPS_ROOT_PATH')) {
    exit();
}

require_once XOOPS_ROOT_PATH . '/core/XCube_ActionForm.class.php';
require_once XOOPS_MODULE_PATH . '/legacy/class/Legacy_Validator.class.php';

class Legacy_SmilesUploadForm extends XCube_ActionForm
{
    public $mOldFileName = null;
    public $_mIsNew = null;
    public $mFormFile = null;
    public $_allowExtensions = ['tar', 'tar.gz', 'tgz', 'gz', 'zip'];

    public function getTokenName()
    {
        return 'module.legacy.SmilesUploadForm.TOKEN';
    }

    public function prepare()
    {
        //
        // Set form properties
        //
        $this->mFormProperties['upload'] =new XCube_FileProperty('upload');
    
        //
        // Set field properties
        //
        $this->mFieldProperties['upload'] =new XCube_FieldProperty($this);
        $this->mFieldProperties['upload']->setDependsByArray(['required']);
        $this->mFieldProperties['upload']->addMessage('required', _AD_LEGACY_ERROR_REQUIRED, _AD_LEGACY_LANG_SMILES_UPLOAD_FILE);
    }
    
    public function validateUpload()
    {
        $formFile = $this->get('upload');
        if (null != $formFile) {
            $flag = false;
            foreach ($this->_allowExtensions as $ext) {
                $flag |= preg_match('/' . str_replace('.', "\.", $ext) . '$/', $formFile->getFileName());
            }
            
            if (!$flag) {
                $this->addErrorMessage(_AD_LEGACY_ERROR_EXTENSION_IS_WRONG);
            }
        }
    }
}
