<?php
/**
 * This Interface is generated by Cube tool.
 * @package   Legacy
 * @version   2.3.0
 * @author    Gigamaster, XCL 2020 PHP7
 * @author    code generator
 * @copyright Copyright 2005-2021 XOOPS Cube Project  <https://github.com/xoopscube/legacy>
 * @license   https://github.com/xoopscube/legacy/blob/master/docs/GPL_V2.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @license   https://github.com/xoopscube/legacy/blob/master/docs/bsd_licenses.txt Modified BSD license
 */

if (!defined('XOOPS_ROOT_PATH')) {
    exit();
}

/**
 * Interface of group client delegate
 * Modules which uses Legacy_Comment must implement this interface.
**/
interface Legacy_iCommentClientDelegate
{
    /**
     * getClientList	Legacy_CommentClient.{dirname}.GetClientList
     *
     * @param mixed[]	&$list
     *  string	$list[]['dirname']	client module's dirname
     *  string	$list[]['dataname']	client module's dataname(tablename)
     *  string	$list[]['access_controller']
     * @param string	$cDirname	comment module's dirname
     *
     * @return	void
     */
    public static function getClientList(/*** mixed[] ***/ &$list, /*** string ***/ $cDirname);
}
